### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by gtkingz** [versx/GoFestController#1]
```
# npm run start

> gofestcontroller@1.0.0 start /home/map/gfc
> node src/index.js

/home/map/gfc/src/services/geofence.js:28
    static instance = new GeofenceService();
                    ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/map/gfc/src/services/route-controller.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gofestcontroller@1.0.0 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gofestcontroller@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-22T09_52_46_798Z-debug.log

```

I didn't setup geofences. Config syntax is looking fine too, absolutely no idea what is going on.

npm -v : 6.13.4
node -v: v10.19.0

**Comment by versx** [comment]
This happens with older versions of node, should work fine with v12 though.

**Comment by gtkingz** [comment]
Thanks :)
